fixes to run ng test
alkemyTech/OT153-CLIENT pull request #108
Opened 2022-03-17 20:29 UTC by federicorojas11

Modifications to run 'ng test'

-> added stylePreprocessorOptions "./src/styles/" on angular.json tests
-> On register.component.ts:
```
import { } from '@angular/google-maps';
    declare const google: any;
```
-> npm install @types/google-maps
-> Other minor changes.

2022-03-17 20:56 UTC, RicardoMaldonado93 requested changes
Please fix the observation to continues with the PR

2022-03-17 20:56 UTC, RicardoMaldonado93 commented on src/app/app.component.spec.ts
> +  // it(`should have as title 'base-ong-angular-client'`, () => {
Si el codigo no sirve/funciona eliminarlo

2022-03-17 22:40 UTC, federicorojas11 commented on src/app/app.component.spec.ts
> +  // it(`should have as title 'base-ong-angular-client'`, () => {
@RicardoMaldonado93 fixed

2022-03-18 13:13 UTC, RicardoMaldonado93 approved these changes
Good job!

2022-03-18 13:13 UTC, merged