Ot153 59 donations and thanks
alkemyTech/OT153-CLIENT pull request #84
Opened 2022-03-13 00:38 UTC by fsalasevicius

## JIRA
[OT153-59](https://alkemy-labs.atlassian.net/browse/OT153-59)

## Short description
Add styles in donations and fix errors with MP
Please add a short description about the changes.

## Screenshot or Video
![donaciones](https://user-images.githubusercontent.com/70928392/158039838-eaea44b7-5556-451b-a5a8-d8f4ab57a311.gif)

Please add a screenshot or video.

## Teammate collaborator

- [ ] Someone from the team collaborated (**_if so, please tag them after this line_**).

### Sanity Check Steps

- [x] All console logs have been removed.
- [x] This change was tested on my localhost.
- [ ] This change depends for another ticket.
- [x] All linked JIRA acceptance criteria are satisfied.
- [ ] Does this change require environment variables.

2022-03-13 00:57 UTC, RicardoMaldonado93 requested changes
Please fix the observations to continues with the PR

2022-03-13 00:57 UTC, RicardoMaldonado93 commented on src/app/features/public/pages/donations/donations.component.html
> +                <a (click)="donar1()"  class="BtnDonationImport BtnDefault">$500</a>
Arreglar la funcion repetida por cada input

2022-03-13 00:57 UTC, RicardoMaldonado93 commented on src/app/features/public/pages/donations/donations.component.ts
> +    donar1(){
refactorizar todas las funciones con donarX()

2022-03-13 06:06 UTC, fsalasevicius commented
![modificacion donaciones](https://user-images.githubusercontent.com/70928392/158047263-da664296-9d66-4f8a-8060-1342a51c790f.jpg)
Optimized functions

2022-03-14 18:12 UTC, RicardoMaldonado93 approved these changes
Amazing!

2022-03-14 18:12 UTC, merged