OT153-96- Alert - Spinner
alkemyTech/OT153-CLIENT pull request #85
Opened 2022-03-13 05:32 UTC by fsalasevicius

## JIRA
[OT153-96](https://alkemy-labs.atlassian.net/browse/OT153-96)

## Short description
Add Alerts, Spinner and Success Dialog

## Screenshot or Video
![spinner (1)](https://user-images.githubusercontent.com/70928392/158046528-c959c699-d4b0-4e57-9128-c13cf7bb8935.gif)

## Teammate collaborator

- [ ] Someone from the team collaborated (**_if so, please tag them after this line_**).

### Sanity Check Steps

- [x] All console logs have been removed.
- [x] This change was tested on my localhost.
- [ ] This change depends for another ticket.
- [x] All linked JIRA acceptance criteria are satisfied.
- [ ] Does this change require environment variables.

2022-03-14 18:31 UTC, RicardoMaldonado93 requested changes
No esta actualizado con develop, no reutiliza componente de dialog y no cumple con los criterios de aceptacion de la tarea

2022-03-15 03:07 UTC, fsalasevicius commented
> No esta actualizado con development, no reutiliza componentes de dialogo y no cumple con los criterios de aceptacion de la tarea

Modificado.

2022-03-15 15:35 UTC, RicardoMaldonado93 commented
@fsalasevicius subi un video con los nuevos cambios porfa

2022-03-15 18:07 UTC, fsalasevicius commented
> @fsalasevicius subi un video con los nuevos cambios porfa

Listo, reemplace el gif por el video.

2022-03-15 18:30 UTC, RicardoMaldonado93 approved these changes
Looks good!

2022-03-15 18:30 UTC, merged